# -*- coding: utf-8 -*-
"""Week 14 Hands-On Challenge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kue0FzLnQhglQMJC3nW8K1FRkCiEKgck
"""

# 1. Install required libraries
!pip install transformers accelerate scipy datasets librosa > /dev/null

import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="huggingface_hub.*")

import torch
import urllib.request
from transformers import pipeline, AutoProcessor, MusicgenForConditionalGeneration
import scipy.io.wavfile

print("Loading Models... this takes about a minute.")

# 2. Load Whisper (Speech to Text)
transcriber = pipeline("automatic-speech-recognition", model="openai/whisper-small", device=0 if torch.cuda.is_available() else -1, chunk_length_s=30)

# 3. Load MusicGen (Text to Music)
processor = AutoProcessor.from_pretrained("facebook/musicgen-small")
music_model = MusicgenForConditionalGeneration.from_pretrained("facebook/musicgen-small")
if torch.cuda.is_available():
    music_model = music_model.to("cuda")

# 4. Define the 8-Axis Agent Logic (Simplified for Demo)
def determine_dna_and_music_prompt(transcription):
    text = transcription.lower()

    # Simple keyword-based DNA extraction
    if any(word in text for word in ["push", "kill", "attack", "fast", "rush"]):
        dna = "Aggressive/Rush"
        music_prompt = "High energy electronic battle music, heavy bass, fast tempo 140 bpm, aggressive synthesizer"
    elif any(word in text for word in ["hide", "wait", "quiet", "stealth", "sniper"]):
        dna = "Stealth/Tactical"
        music_prompt = "Dark ambient, tense strings, slow tempo, quiet atmospheric thriller music"
    else:
        dna = "Casual/Exploration"
        music_prompt = "Lo-fi chill gaming beats, relaxing, ambient, peaceful synthesizer"

    return dna, music_prompt

# 5. Execute Pipeline (Simulating player audio)
# (In a real scenario, you upload a .wav file. Here we use a sample from HuggingFace for speed)
print("\n--- Running Multimodal Pipeline ---")
audio_url = "https://huggingface.co/datasets/Narsil/asr_dummy/resolve/main/mlk.flac" # Placeholder audio
urllib.request.urlretrieve(audio_url, "mlk.flac") # Download locally to avoid streaming issues
transcription = transcriber("mlk.flac")["text"]
print(f"1. Whisper Transcription: '{transcription}'")

# Override transcription for the sake of the gaming demo
simulated_voice_chat = "We need to push them now! Attack the base, go fast!"
print(f"1b. Simulated Gamer Chat: '{simulated_voice_chat}'")

dna, music_prompt = determine_dna_and_music_prompt(simulated_voice_chat)
print(f"2. Extracted Player DNA: {dna}")
print(f"3. Generated Music Prompt: {music_prompt}")

# 6. Generate Soundtrack
print("4. Generating Custom Soundtrack with MusicGen... (Takes ~10-20 seconds)")
inputs = processor(text=[music_prompt], padding=True, return_tensors="pt")
if torch.cuda.is_available():
    inputs = {k: v.to("cuda") for k, v in inputs.items()}

audio_values = music_model.generate(**inputs, max_new_tokens=256)

# 7. Save Output
sampling_rate = music_model.config.audio_encoder.sampling_rate
audio_data = audio_values[0, 0].cpu().numpy()
scipy.io.wavfile.write("custom_player_soundtrack.wav", rate=sampling_rate, data=audio_data)
print("5. DONE! Saved as 'custom_player_soundtrack.wav'.")

!pip install weasyprint > /dev/null
from weasyprint import HTML
import base64

html_content = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page {
            size: 16in 9in;
            margin: 0;
            background-color: #0b110d; /* Deep dark green-black for gaming aesthetic */
        }
        body {
            margin: 0;
            padding: 0;
            font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            color: #e4e9e5;
            background-color: #0b110d;
        }
        .slide {
            width: 16in;
            height: 9in;
            position: relative;
            page-break-after: always;
            padding: 1.2in 1.5in;
            box-sizing: border-box;
            background-color: #0b110d;
            overflow: hidden;
        }
        /* Aesthetic Gaming Accent - Sage/Olive Neon */
        .accent-top {
            position: absolute;
            top: 0;
            left: 0;
            width: 16in;
            height: 8px;
            background: linear-gradient(90deg, #4f7754, #85b08b, #4f7754);
        }
        .accent-glow {
            position: absolute;
            top: 8px;
            left: 0;
            width: 16in;
            height: 40px;
            background: linear-gradient(180deg, rgba(133, 176, 139, 0.15) 0%, rgba(11, 17, 13, 0) 100%);
        }
        /* Grid background subtle effect */
        .grid-bg {
            position: absolute;
            top: 0; left: 0; right: 0; bottom: 0;
            background-image:
                linear-gradient(rgba(133, 176, 139, 0.03) 1px, transparent 1px),
                linear-gradient(90deg, rgba(133, 176, 139, 0.03) 1px, transparent 1px);
            background-size: 50px 50px;
            z-index: 0;
        }
        .content {
            position: relative;
            z-index: 1;
        }

        /* Typography */
        h1 {
            font-size: 52pt;
            color: #85b08b; /* Sage green accent */
            margin-bottom: 0.1in;
            margin-top: 1in;
            font-weight: 700;
            letter-spacing: 2px;
        }
        h2 {
            font-size: 38pt;
            color: #85b08b;
            border-bottom: 2px solid #2a3a2d;
            padding-bottom: 0.2in;
            margin-top: 0;
            margin-bottom: 0.4in;
            font-weight: 600;
            letter-spacing: 1px;
        }
        .subtitle {
            font-size: 26pt;
            color: #a3bba7;
            margin-bottom: 1.5in;
            font-weight: 300;
            letter-spacing: 1px;
        }
        .author-info {
            font-size: 22pt;
            color: #7b8f80;
            border-left: 4px solid #85b08b;
            padding-left: 0.3in;
        }
        p, li {
            font-size: 22pt;
            line-height: 1.6;
            margin-bottom: 0.25in;
            color: #d1d8d3;
        }
        ul {
            margin-left: 0.5in;
            margin-top: 0;
        }
        li::marker {
            color: #85b08b;
        }
        .highlight {
            color: #a4e0b0;
            font-weight: bold;
        }

        /* Layout Utilities */
        .footer {
            position: absolute;
            bottom: 0.5in;
            left: 1.5in;
            right: 1.5in;
            font-size: 14pt;
            color: #4a5c4e;
            border-top: 1px solid #1e2b21;
            padding-top: 0.2in;
            z-index: 1;
        }
        .slide-number {
            position: absolute;
            bottom: 0.5in;
            right: 1.5in;
            font-size: 14pt;
            color: #4a5c4e;
            z-index: 1;
            padding-top: 0.2in;
        }

        /* Special layout for two column look */
        .col-left {
            position: absolute;
            left: 1.5in;
            width: 6in;
            top: 2.2in;
        }
        .col-right {
            position: absolute;
            left: 8in;
            width: 6.5in;
            top: 2.2in;
        }
    </style>
</head>
<body>

    <div class="slide">
        <div class="grid-bg"></div>
        <div class="accent-top"></div>
        <div class="accent-glow"></div>
        <div class="content" style="text-align: center; margin-top: 0.5in;">
            <h1 style="font-size: 65pt; text-transform: uppercase; text-shadow: 0 0 20px rgba(133,176,139,0.3);">SonicGen</h1>
            <div class="subtitle" style="font-size: 32pt; margin-bottom: 1.2in;">Audio-Driven Player DNA & Dynamic Soundtrack AI</div>

            <div style="display: inline-block; text-align: left; background: rgba(30,43,33,0.6); padding: 0.5in; border-radius: 8px; border: 1px solid #2a3a2d;">
                <div style="font-size: 26pt; color: #e4e9e5; margin-bottom: 0.1in; font-weight: bold;">Prathyusha Ragav Adari</div>
                <div style="font-size: 20pt; color: #85b08b;">M.S. Data Science, UMKC</div>
                <div style="font-size: 18pt; color: #6a7c6e; margin-top: 0.2in;">Foundation Models for Speech, Music, and Sound AI</div>
            </div>
        </div>
    </div>

    <div class="slide">
        <div class="grid-bg"></div>
        <div class="accent-top"></div>
        <div class="content">
            <h2>The Problem Space</h2>
            <p>Modern video games utilize <span class="highlight">static soundtracks</span> that fail to adapt to individual player behaviors, emotional states, or real-time tactical decisions.</p>
            <p>Furthermore, current player profiling relies heavily on rigid telemetry data:</p>
            <ul>
                <li>Kill/Death Ratios</li>
                <li>Movement Speed & Heatmaps</li>
                <li>Objective Completion Rates</li>
            </ul>
            <p style="margin-top: 0.5in; border-left: 4px solid #85b08b; padding-left: 0.3in; background: rgba(133,176,139,0.05); padding: 0.2in;">
                <strong>The Gap:</strong> These metrics ignore the most direct indicator of player intent and state—<span class="highlight">how they communicate</span> via voice chat.
            </p>
        </div>
        <div class="footer">SonicGen Pipeline</div>
        <div class="slide-number">2</div>
    </div>

    <div class="slide">
        <div class="grid-bg"></div>
        <div class="accent-top"></div>
        <div class="content">
            <h2>The Solution & Business Value</h2>
            <p>An AI system that ingests a player's voice communications, extracts an <span class="highlight">8-Axis Gamer DNA profile</span>, and dynamically generates custom background music to match their exact playstyle.</p>

            <div style="margin-top: 0.6in;">
                <p><strong>Value Proposition:</strong></p>
                <ul>
                    <li><span class="highlight">Enhanced Immersion:</span> Players remain in a "flow state" longer when auditory feedback matches their emotional intensity.</li>
                    <li><span class="highlight">Player Retention:</span> Hyper-personalized gaming experiences increase overall Lifetime Value (LTV) and session length.</li>
                    <li><span class="highlight">Esports & Streaming:</span> Content creators automatically receive copyright-free, adaptive background music tailored to their gameplay intensity.</li>
                </ul>
            </div>
        </div>
        <div class="footer">SonicGen Pipeline</div>
        <div class="slide-number">3</div>
    </div>

    <div class="slide">
        <div class="grid-bg"></div>
        <div class="accent-top"></div>
        <div class="content">
            <h2>Dataset & Inputs</h2>
            <p>To evaluate the pipeline, we utilized simulated voice communication data designed to mimic real-world gaming environments.</p>

            <ul>
                <li><span class="highlight">Speech Input:</span> 10-second simulated audio clips of player voice chat over standard comms channels.</li>
                <li><span class="highlight">Scenario A (Aggressive):</span> "Push mid, they're weak! Flank them right now!"</li>
                <li><span class="highlight">Scenario B (Tactical/Calm):</span> "Let's just gather resources and build a base quietly. Watch the perimeter."</li>
            </ul>

            <p style="margin-top: 0.4in;"><strong>Target Output:</strong></p>
            <p>10-second custom AI-generated soundtracks mapped to the deduced behavioral DNA.</p>
        </div>
        <div class="footer">SonicGen Pipeline</div>
        <div class="slide-number">4</div>
    </div>

    <div class="slide">
        <div class="grid-bg"></div>
        <div class="accent-top"></div>
        <div class="content">
            <h2>Pipeline Architecture</h2>

            <p><span class="highlight">Phase 1: Speech-to-Text</span><br>
            Using <code>openai/whisper-small</code> to accurately transcribe the raw player voice chat, handling varying speeds and intensities.</p>

            <p><span class="highlight">Phase 2: DNA Extraction (Agentic Logic)</span><br>
            An NLP logic layer analyzes the transcription to determine the "8-Axis Gamer DNA" (e.g., Aggression, Tactical, Stealth, Chaos) and synthesizes a highly descriptive music prompt.</p>

            <p><span class="highlight">Phase 3: Music Generation</span><br>
            Using <code>facebook/musicgen-small</code> to take the synthesized prompt and render a seamless, customized soundtrack on the fly.</p>
        </div>
        <div class="footer">SonicGen Pipeline</div>
        <div class="slide-number">5</div>
    </div>

    <div class="slide">
        <div class="grid-bg"></div>
        <div class="accent-top"></div>
        <div class="content">
            <h2>Prompt & Input Engineering</h2>
            <p>Effective generation requires translating abstract player states into concrete audio engineering parameters.</p>

            <div style="background: rgba(30,43,33,0.5); padding: 0.3in; border-radius: 8px; margin-bottom: 0.3in;">
                <p style="margin-top:0;"><strong>High Aggression DNA Mapping:</strong><br>
                <em>Prompt:</em> "Heavy bass, fast tempo 140bpm, aggressive synth, cyberpunk, high energy battle sequence."</p>
            </div>

            <div style="background: rgba(30,43,33,0.5); padding: 0.3in; border-radius: 8px;">
                <p style="margin-top:0;"><strong>High Stealth / Calm DNA Mapping:</strong><br>
                <em>Prompt:</em> "Dark ambient, slow tempo, tense strings, quiet atmospheric thriller music, sparse percussion."</p>
            </div>
        </div>
        <div class="footer">SonicGen Pipeline</div>
        <div class="slide-number">6</div>
    </div>

    <div class="slide">
        <div class="grid-bg"></div>
        <div class="accent-top"></div>
        <div class="content">
            <h2>Evaluation Methodology</h2>

            <p><strong>Baseline vs. Improved Pipeline</strong></p>
            <ul>
                <li><span class="highlight">Baseline:</span> Feeding MusicGen generic static prompts (e.g., "video game combat music").</li>
                <li><span class="highlight">Improved:</span> Injecting the dynamically extracted 8-Axis DNA prompt structure mapped to BPM and specific instrument clusters.</li>
            </ul>

            <p style="margin-top: 0.4in;"><strong>Key Metrics Tracked</strong></p>
            <ul>
                <li><span class="highlight">Whisper WER (Word Error Rate):</span> Evaluated transcription accuracy on gaming-specific slang and rapid speech.</li>
                <li><span class="highlight">Music Prompt Alignment:</span> Qualitative evaluation of whether the generated audio matched the detected emotional state of the voice chat.</li>
            </ul>
        </div>
        <div class="footer">SonicGen Pipeline</div>
        <div class="slide-number">7</div>
    </div>

    <div class="slide">
        <div class="grid-bg"></div>
        <div class="accent-top"></div>
        <div class="content">
            <h2>Results & Insights</h2>

            <ul>
                <li><strong>Finding 1:</strong> <code>Whisper</code> struggles slightly with highly niche gaming slang without specific fine-tuning, but it perfectly captures the <span class="highlight">general intent and action verbs</span> necessary for DNA profiling.</li>
                <br>
                <li><strong>Finding 2:</strong> <code>MusicGen</code> responds remarkably well to explicit BPM (Beats Per Minute) and genre tags triggered by the Agentic DNA logic, producing reliable stylistic shifts.</li>
                <br>
                <li><strong>Conclusion:</strong> Multimodal chaining (Speech → Text → Music) successfully circumvents static game design, allowing for highly coherent, real-time audio personalization.</li>
            </ul>
        </div>
        <div class="footer">SonicGen Pipeline</div>
        <div class="slide-number">8</div>
    </div>

    <div class="slide">
        <div class="grid-bg"></div>
        <div class="accent-top"></div>
        <div class="content">
            <h2>Limitations & Future Work</h2>

            <p><strong>Current Limitations:</strong></p>
            <ul>
                <li><span class="highlight">Compute Latency:</span> MusicGen requires several seconds to generate audio segments. This currently limits instantaneous, split-second in-game adaptation without pre-buffering.</li>
            </ul>

            <p style="margin-top: 0.4in;"><strong>Future Expansions:</strong></p>
            <ul>
                <li><span class="highlight">Granular Sound Effects:</span> Integrating <code>AudioLDM2</code> to generate specific, one-off sound effects (e.g., customized weapon sounds or alert pings) based on the same continuous Player DNA profile.</li>
                <li><span class="highlight">Continuous Profiling:</span> Implementing graph machine learning to map player DNA evolution over long campaign playtimes.</li>
            </ul>
        </div>
        <div class="footer">SonicGen Pipeline</div>
        <div class="slide-number">9</div>
    </div>

    <div class="slide">
        <div class="grid-bg"></div>
        <div class="accent-top"></div>
        <div class="content">
            <h2>Links & AI Disclosure</h2>

            <p><strong>Project Resources:</strong></p>
            <ul>
                <li><span class="highlight">GitHub Repository:</span> Available via Canvas Submission</li>
                <li><span class="highlight">Demo Video:</span> Attached in Canvas portal</li>
            </ul>

            <p style="margin-top: 0.5in;"><strong>AI Tool Disclosure:</strong></p>
            <p style="font-size: 18pt; line-height: 1.4; background: rgba(30,43,33,0.4); padding: 0.3in; border-left: 3px solid #85b08b;">
                This project utilized Hugging Face for pretrained open-source models (Whisper-small, MusicGen-small). Google Colab was used for GPU compute and pipeline execution. AI assistants (ChatGPT/Claude) were utilized to assist in structuring the Python pipeline architecture, debugging tensor processing, and generating boilerplate presentation text.
            </p>
        </div>
        <div class="footer">SonicGen Pipeline</div>
        <div class="slide-number">10</div>
    </div>

    <div class="slide">
        <div class="grid-bg"></div>
        <div class="accent-top"></div>
        <div class="accent-glow"></div>
        <div class="content">
            </div>
        <div class="footer">SonicGen Pipeline - Appendix</div>
        <div class="slide-number">11</div>
    </div>

    <div class="slide">
        <div class="grid-bg"></div>
        <div class="accent-top"></div>
        <div class="accent-glow"></div>
        <div class="content">
            </div>
        <div class="footer">SonicGen Pipeline - Appendix</div>
        <div class="slide-number">12</div>
    </div>

</body>
</html>
"""

with open("presentation.html", "w") as f:
    f.write(html_content)

HTML(filename="presentation.html").write_pdf("SonicGen_Presentation.pdf")
print("PDF Presentation generated successfully.")